apiVersion: v1
kind: Service
metadata:
  name: app-api
  namespace: hyperdx
  labels:
    app.kubernetes.io/name: app-api
    app.kubernetes.io/part-of: hyperdx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app-api
  ports:
    - name: app
      port: 8080
      targetPort: app
      nodePort: 30800
    - name: api
      port: 8000
      targetPort: api
    - name: opamp
      port: 4320
      targetPort: opamp
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: hyperdx
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: hyperdx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      nodePort: 30417
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      nodePort: 30418
    - name: health
      port: 13133
      targetPort: health
    - name: metrics
      port: 8888
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: hyperdx
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: hyperdx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: hyperdx
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: hyperdx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
